# Generated by Django 5.1.1 on 2025-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_reg1', models.FloatField(default=0.0)),
                ('holding_reg2', models.FloatField(default=0.0)),
                ('holding_reg3', models.FloatField(default=0.0)),
                ('holding_reg4', models.FloatField(default=0.0)),
                ('holding_reg5', models.FloatField(default=0.0)),
                ('holding_reg6', models.FloatField(default=0.0)),
                ('holding_reg7', models.FloatField(default=0.0)),
                ('holding_reg8', models.FloatField(default=0.0)),
                ('holding_reg9', models.FloatField(default=0.0)),
                ('holding_reg10', models.FloatField(default=0.0)),
                ('holding_reg11', models.FloatField(default=0.0)),
                ('holding_reg12', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
