# Generated by Django 5.1.1 on 2025-01-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='Inverter1Data',
        ),
    ]
